config/routes.rb
Rails.application.routes.draw do
  get 'documentaryfilms/index' 
  get 'documentaryfilms/new'

  get 'series/index' 
  get 'series/new'
  
  get 'movies/index'
  get 'movies/new'

  post "/documentaryfilms/create"=>"documentaryfilms#create"
  post "/series/create"=>"series#create"
  post "/movies/create"=>"movies#create"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 
  get '/movies', to: 'movies#index'
  get '/movies/new', to: 'movies#new'
  post '/movies', to: 'movies#create'

  get '/series', to: 'series#index'
  get '/series/new', to: 'series#new'
  post '/series', to: 'series#create'

  get '/documentary_films', to: 'documentary_films#index'
  get '/documentary_films/new', to: 'documentary_films#new'
  post '/documentary_films', to: 'documentary_films#create'

  
  # Defines the root path route ("/")
  root "movies#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/models/serie.rb
class Serie < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentary_films_controller.rb
class DocumentaryFilmsController < ApplicationController

  def index
    @documentary_films = DocumentaryFilm.all
  end

  def new
    @documentary_film = DocumentaryFilm.new
  end

  def create
    @documentary_film = DocumentaryFilm.new(documentary_film_params)
    if @documentary_film.save
      redirect_to documentary_films_path, notice: 'Documental creado.'
    else
      render :new
    end
  end

  private

  def documentary_film_params
    params.require(:documentary_films).permit(:name, :synopsis, :director)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies=Movie.all
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_index_path
    else
      render :new
    end   
  end

  def new
    @movie = Movie.new
  end
  
  def movie_params
    params.require(:movie).permit(:name, :synopsis, :director)
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @series=Serie.all
  end

  def create
    @series=Serie.new(series_params)
    if @series.save
      redirect_to series_index_path
    else 
      render :new
    end
  end

  def new
    @serie=Serie.new
  end

  private
  def series_params
    params.require(:serie).permit(:name, :synopsis, :director)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_films_helper.rb
module DocumentaryFilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentary_films/index.html.erb
<h1>Documentales de...</h1>

<%= link_to 'Ingresar un nuevo Documental', documentary_films_new_path %>

<div>
<table class="custom-table">
    <thead>
        <tr>
        <th scope="col">N°</th>
        <th scope="col">Nombre del Documental</th>
        <th scope="col">Sinopsis</th>
        <th scope="col">Director</th>
        </tr>
    </thead>
        <tbody class="table-group-divider">
        <% @documentary_films.each do |documentaryfilm| %>
        <tr>
        <th scope="row"><%= documentaryfilm.id %></th>
        <strong>Name:</strong> <%= documentary_film.name %><br>
        <strong>Synopsis:</strong> <%= documentary_film.synopsis %><br>
        <strong>Director:</strong> <%= documentary_film.director %> <br>
        </tr>
        <% end %>
        </tbody>
</table>
</div>

app/views/documentary_films/new.html.erb
<h1>Nuevo Documental </h1>  

<%= form_with url: documentaryfilms_create_path, model: @documentaryfilm, method: :post do |form| %>
  <div>
    <%= form.label :name, "Ingresa Tu Documental", class: "form-label" %> <br>
    <%= form.text_field :name %> <br>
  </div>
  <div>
    <%= form.label :synopsis, "Synopis", class: "form-label" %> <br>
    <%= form.text_area :synopsis %> <br>
  </div>
  <div>
    <%= form.label :director, "El Director", class: "form-label" %> <br>
    <%= form.text_field :director %> <br>
  </div>
  <br>
  <div>
    <%= form.submit "Guardar" %>
  </div>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300;400;500;600;700&family=Raleway:ital@1&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css', crossorigin: 'anonymous' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Nav -->
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="btn-group" role="group" aria-label="Basic outlined example">
        <button type="button" class="btn btn-outline-primary">Aplicacion de Entretenimiento</button>
        <%= link_to movies_path, class: "btn btn-outline-primary" do %>
          Películas
        <% end %>
        <%= link_to series_path, class: "btn btn-outline-primary" do %>
          Series
        <% end %>
        <%= link_to documentary_films_path, class: "btn btn-outline-primary" do %>
          Documentales
        <% end %>
      </div>
    </nav> 
  
    <div class="container mt-5"><%= yield %></div><br>

      <footer>
        <br>&copy; <%= Time.current.year %> Your Application. All rights reserved. Mariela Vega
      </footer>
  </body>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</html>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>
<h1>Película creada exitosamente</h1>

<p>Nombre: <%= @movie.name %></p>
<p>Sinopsis: <%= @movie.synopsis %></p>
<p>Director: <%= @movie.director %></p>

<%= link_to 'Volver al listado', movies_path %>

app/views/movies/index.html.erb
<h1>Peliculas</h1>
<h1> Lista de... </h1>


<%= link_to 'Ingresar una nueva Pelicula', movies_new_path %>

<div>
    <table class="custom-table">
        <thead>
            <tr>
                <th scope="col">N°</th>
                <th scope="col">Nombre de la Movie</th>
                <th scope="col">Sinopsis</th>
                <th scope="col">Director</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            <% @movies.each do |movie| %>
            <tr>
                <th scope="row"><%= movie.id %></th>
                <td><%= movie.name %></>
                <td><%= movie.synopsis %></td>
                <td><%= movie.director %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>

app/views/movies/new.html.erb
<h1>Nueva Movie</h1>

<%= form_with url: movies_create_path, model: @movie, method: :post do |form| %>

  <%= form.label :name, "Ingresa Tu Pelicula", class: "form-label" %> <br>
  <%= form.text_field :name %> <br>

  <%= form.label :synopsis, "Synopsis", class: "form-label" %> <br>
  <%= form.text_area :synopsis %> <br>

  <%= form.label :director, "El Director",class: "form-label" %> <br>
  <%= form.text_field :director %> <br>
  <br>
  <%= form.submit "Crear nueva pelicula" %> <br>
  
<% end %>

app/views/series/create.html.erb
<h1>Series#create</h1>
<p>Find me in app/views/series/create.html.erb</p>

app/views/series/index.html.erb
  <div class="container">
    <h1>Series</h1>

          <h3>Las 10 mejores de series</h3><br>
          
<%= link_to 'Ingresar una nueva Serie', series_new_path %>
          <table class="custom-table">
            <thead>
                <tr>
                    <th scope="col">N°</th>
                    <th scope="col">Nombre de la Serie</th>
                    <th scope="col">Sinopsis</th>
                    <th scope="col">Director</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                <% @series.each do |serie| %>
                <tr>
                    <th scope="row"><%= serie.id %></th>
                    <td><%= serie.name %></>
                    <td><%= serie.synopsis %></td>
                    <td><%= serie.director %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
      
  </div>

app/views/series/new.html.erb
<h1>Nuevas Series</h1>

<%= form_with url: series_create_path, model: @serie, method: :post do |form| %>

  <div>
    <%= form.label :name, "Ingresa Tu Serie", class: "form-label" %> <br>
    <%= form.text_field :name %> <br>
  </div>

  <div>
    <%= form.label :synopsis, "Cuentame de tu serie", class: "form-label" %> <br>
    <%= form.text_area :synopsis %> <br>
  </div>

  <div>
    <%= form.label :director, "El Director", class: "form-label" %> <br>
    <%= form.text_field :director %> <br>
    <br>
  </div>

  <div>
    <%= form.submit "Guardar" %>
  </div>

<% end %>